POST {{domain}}/api/users
Content-Type: application/json

{
  "user":{
    "username": "Jacob",
    "email": "jake@jake.jake",
    "password": "jakejake"
  }
}

###
POST http://localhost:8001/api/users
Content-Type: application/json

{
  "user": {
    "username": "juniq",
    "email": "juniq@juniq.juniq",
    "password": "juniqjuniq"
  }
}

###
GET http://localhost:8001/api/user
Content-Type: application/json
Authorization: Token eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzUxMiJ9.eyJleHAiOjMxNTM2MDAwLCJqdGkiOiJ3cjRQWUNvZGRBYmk2bk5NM1BjQnp3IiwiaWF0IjoxNjY2NTI5MTUwfQ.L9ybjoP3yVJtK1X1-MU_8ujVDHSuEO7SsI5VqGLsm3vs6vC6hXh56UnLm_uZLaksPlLTx7puI94Bj6kjp2625qJfVEOmfsp26wNrRNOlHjeAbEToCcC0-AEo_z_mid4uSQORVBI5tPFLfQ3m-62e_IUQ5xignFq7mx9UzRiDCGFkOxEWDUvz1aILAH-NZRy4tZqnXcUI7IOoUAtZWEKd9pRK1qE__udGucrSV8ocM-UJ2oRtmRG3XxMi1ZNdI-8oXyumfd58aLlMdmM_fMcqROYpKbVXjUUlKQfAS0wVPBNrio8gEPE9FQi7I7AFS4AHGdhvREEH12mFr9AYOZICmw

###
POST http://localhost:8001/api/users/login
Content-Type: application/json

{
  "user":{
    "email": "jake@jake.jake",
    "password": "jakejake"
  }
}


###
PUT http://localhost:8001/api/user
Content-Type: application/json
Authorization: Token eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzUxMiJ9.eyJleHAiOjMxNTM2MDAwLCJqdGkiOiJDOGQ1ZC1WNjJvX2l3TnpIQ1JtLWl3IiwiaWF0IjoxNjY2NTA5MjA2fQ.QHJz72GrVRRxsczyeo3tEoBpKGyErrc-_gnz5IOZmOmzDpke91NdeAQKcQfyByJ9Iq5ap2V3VTwhEtEUg-jF1u88vi7S7ZcsH5lDQ1k_NHoThXd0d9cAnetcC8dwFRQpyxX3bHKQcPOlSww3USKKvFZxcR7AsXkvCOABnvcXJ_02ZslGckuKZa87IErxm3FnKhE9X-RE9TOP-At7XOcUkPq3Ah_MOT4C6ZDiNN1S836W239Gf-Vuzi-O003WfipbUlnwWTbqGGo1AG6FAiTMc_ZWPjbk6NbZDYEr823rFg9HUuJRDnmJwSpDTIS2at60Bo5-Hu3NXT2bs3LoYO1Lyw

{
  "user":{
    "email": "jake@jake.jake",
    "bio": "I like to skateboard",
    "image": "https://i.stack.imgur.com/xHWG8.jpg"
  }
}

###
POST http://localhost:8001/api/profiles/juniq/follow
Content-Type: application/json
Authorization: Token eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzUxMiJ9.eyJleHAiOjMxNTM2MDAwLCJqdGkiOiJHMDl0NmNiTXBma2pYMzZqNk5JMVZBIiwiaWF0IjoxNjY3Mjc1ODY4fQ.U2ti8R-TYxzNqCiWu_7Z6wP3rS3FSFTqGzIhL3c3wO9wk3NVzxR8XDLWbS5GQIr5xVozADVJ1Y1xsoq2eGGlQukKleQxgRwZTbA2x5A1Z4dSwe3qQMEF002oa8J0n2v0XmMvheLwYgIJjKSL-xbv8S3pyeB02002qs9gqTsd92LS9Y8aV-6E5nu8Bej1HR-OKIPpSvOUhRea2jTbNCNJaH7g4AW06lTYkcnXLMK250SG46hWLeMIS31ZFyKXmNONloO0ppIu0Dpw2INcZe9GDoyi05o9lwh1yKtPoidvMY8djFpBGEGau3oNQxAwQhKaQ4Qltv6ZhRdoKHIjcdcZhw

###
GET http://localhost:8001/api/profiles/juniq
Content-Type: application/json
Authorization: Token eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzUxMiJ9.eyJleHAiOjMxNTM2MDAwLCJqdGkiOiJHMDl0NmNiTXBma2pYMzZqNk5JMVZBIiwiaWF0IjoxNjY3Mjc1ODY4fQ.U2ti8R-TYxzNqCiWu_7Z6wP3rS3FSFTqGzIhL3c3wO9wk3NVzxR8XDLWbS5GQIr5xVozADVJ1Y1xsoq2eGGlQukKleQxgRwZTbA2x5A1Z4dSwe3qQMEF002oa8J0n2v0XmMvheLwYgIJjKSL-xbv8S3pyeB02002qs9gqTsd92LS9Y8aV-6E5nu8Bej1HR-OKIPpSvOUhRea2jTbNCNJaH7g4AW06lTYkcnXLMK250SG46hWLeMIS31ZFyKXmNONloO0ppIu0Dpw2INcZe9GDoyi05o9lwh1yKtPoidvMY8djFpBGEGau3oNQxAwQhKaQ4Qltv6ZhRdoKHIjcdcZhw

###
DELETE http://localhost:8001/api/profiles/juniq/follow
Content-Type: application/json
Authorization: Token eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzUxMiJ9.eyJleHAiOjMxNTM2MDAwLCJqdGkiOiJHMDl0NmNiTXBma2pYMzZqNk5JMVZBIiwiaWF0IjoxNjY3Mjc1ODY4fQ.U2ti8R-TYxzNqCiWu_7Z6wP3rS3FSFTqGzIhL3c3wO9wk3NVzxR8XDLWbS5GQIr5xVozADVJ1Y1xsoq2eGGlQukKleQxgRwZTbA2x5A1Z4dSwe3qQMEF002oa8J0n2v0XmMvheLwYgIJjKSL-xbv8S3pyeB02002qs9gqTsd92LS9Y8aV-6E5nu8Bej1HR-OKIPpSvOUhRea2jTbNCNJaH7g4AW06lTYkcnXLMK250SG46hWLeMIS31ZFyKXmNONloO0ppIu0Dpw2INcZe9GDoyi05o9lwh1yKtPoidvMY8djFpBGEGau3oNQxAwQhKaQ4Qltv6ZhRdoKHIjcdcZhw