POST {{domain}}/api/articles
Content-Type: application/json
Authorization: Token eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzUxMiJ9.eyJleHAiOjMxNTM2MDAwLCJqdGkiOiJpVVg4aDNaV3lPdTlYWGtHRGpxY2VRIiwiaWF0IjoxNjcwODM3ODY0fQ.gDBE5tIS8k8zmih12Zhoq3xpr_5NHRB_NbxAr7w1P6AYLB4iAbNkjcflRys99MF-pdzfyBGB7Ln2_s3P5NV5qpswrQldL09d0cdYtkJFk4orP4i3Uo0ErZzsq0TlDrqZ4ATRs59O7LpldPTyNyGEEFhOCH8OJlBwaQDZaHj6OIKQElIT9elThpo4gM9RbVM-7xFuPMy5WESZFzeOK-CCz2H70tTnzyCtU2B7wGbRSyul6JViQZ4RW_vFL5c0C3SJgPMdGAFRwnbYD_CqiXV0GkurXgmJmIi0Y_UFtISuCTGMEyKeCfNu6huceXWFeoWjDtfXlOgaEs04bLcf6DclyQ

{
  "article": {
    "title": "How to train your dragon",
    "description": "Ever wonder how?",
    "body": "You have to believe",
    "tagList": ["reactjs", "angularjs", "dragons"]
  }
}

###
PUT {{domain}}/api/articles/how-to-train-your-dragon
Content-Type: application/json
Authorization: Token eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzUxMiJ9.eyJleHAiOjMxNTM2MDAwLCJqdGkiOiJpVVg4aDNaV3lPdTlYWGtHRGpxY2VRIiwiaWF0IjoxNjcwODM3ODY0fQ.gDBE5tIS8k8zmih12Zhoq3xpr_5NHRB_NbxAr7w1P6AYLB4iAbNkjcflRys99MF-pdzfyBGB7Ln2_s3P5NV5qpswrQldL09d0cdYtkJFk4orP4i3Uo0ErZzsq0TlDrqZ4ATRs59O7LpldPTyNyGEEFhOCH8OJlBwaQDZaHj6OIKQElIT9elThpo4gM9RbVM-7xFuPMy5WESZFzeOK-CCz2H70tTnzyCtU2B7wGbRSyul6JViQZ4RW_vFL5c0C3SJgPMdGAFRwnbYD_CqiXV0GkurXgmJmIi0Y_UFtISuCTGMEyKeCfNu6huceXWFeoWjDtfXlOgaEs04bLcf6DclyQ

{
  "article": {
    "title": "Did you train your dragon?"
  }
}

###
GET {{domain}}/api/articles/how-to-train-your-dragon

###
DELETE {{domain}}/api/articles/how-to-train-your-dragon
Content-Type: application/json
Authorization: Token eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzUxMiJ9.eyJleHAiOjMxNTM2MDAwLCJqdGkiOiJqWnpscThiMWl1ZFRyNC1lajFYc0dBIiwiaWF0IjoxNjcwODM2ODYyfQ.Qi_b0fzKMf5hPZfnzbt1RQ4-GTOzwI_KWrYvbZDhJKUy5If2042HF4jmtNC1zlytDeKunJoLOQPUuwCN0TY5R_wpztyOGwDvgy6RBwKViNCdQNLCiksVxsrHq-uhZ2W2kp2yu_JxwcWFj8jQQhdPQmv71Wwtj2rzcwX-Pv5aNVSPsswSx2_cwd46AvFMyMj5srS_U5eytCtEp4VrkFhnBl8423zrvLs26uOAgQjWECThitvkHgBflG8pkoe8ZryWEOyd9-fNKmHotXd5U1XXUlP591dBPaFbwV5PNWzrvbu5ZoIMnqDVCgAqtcEPzLwQonGE3P3DsAnhErC5_bu7zQ