POST {{domain}}/api/articles
Content-Type: application/json
Authorization: Token eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzUxMiJ9.eyJleHAiOjMxNTM2MDAwLCJqdGkiOiJ1dHVNNldvQjB1aEtLY0xFRm1QLUNRIiwiaWF0IjoxNjcwODM0Nzk2fQ.XlJy3fNHN1TLIpEPSYhbmCd5xSu7B7_59-AgcFb6aa5VZlb2EOZEq5d5gdRQMMuA3mZGgcP9Sb18u2LC4g2mo6SSqeozdcF8R99MYRqcKHrtKRtl_QNOmf90MOPgTNKj5hSKBiwX7YYf8DZSuxATWMoL_dtugqUv5OiZsc_bT_8WCzARuDgokluctT8OjkXGyPYesWx2gW6Z7-XanfgerE4RSxAyQuOcuJspry4A9MPBd9_S-nSoT663Uamip907QURSJDvMG3xbNCgxXXfKjJnGaXRuIwJq81JjOqYKh7oof5dzXwHy1TrPQaFZuig8hPO0GwZEMNWMLItb5V-nhw

{
  "article": {
    "title": "How to train your dragon",
    "description": "Ever wonder how?",
    "body": "You have to believe",
    "tagList": ["reactjs", "angularjs", "dragons"]
  }
}

###
PUT {{domain}}/api/articles/how-to-train-your-dragon
Content-Type: application/json
Authorization: Token eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzUxMiJ9.eyJleHAiOjMxNTM2MDAwLCJqdGkiOiJ1dHVNNldvQjB1aEtLY0xFRm1QLUNRIiwiaWF0IjoxNjcwODM0Nzk2fQ.XlJy3fNHN1TLIpEPSYhbmCd5xSu7B7_59-AgcFb6aa5VZlb2EOZEq5d5gdRQMMuA3mZGgcP9Sb18u2LC4g2mo6SSqeozdcF8R99MYRqcKHrtKRtl_QNOmf90MOPgTNKj5hSKBiwX7YYf8DZSuxATWMoL_dtugqUv5OiZsc_bT_8WCzARuDgokluctT8OjkXGyPYesWx2gW6Z7-XanfgerE4RSxAyQuOcuJspry4A9MPBd9_S-nSoT663Uamip907QURSJDvMG3xbNCgxXXfKjJnGaXRuIwJq81JjOqYKh7oof5dzXwHy1TrPQaFZuig8hPO0GwZEMNWMLItb5V-nhw

{
  "article": {
    "title": "Did you train your dragon?"
  }
}
