POST {{domain}}/api/articles
Content-Type: application/json
Authorization: Token eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzUxMiJ9.eyJleHAiOjMxNTM2MDAwLCJqdGkiOiJTZkx3UHlndmlmWUI0UFRsVEhnS0ZnIiwiaWF0IjoxNjcwODM3MDQ2fQ.LvbRnX9HN94NdYqYZxmkdyVoUIb3umAnjHhqQ-9QY98StxQSqayp2oIS1lPHljL1LFB06-IPLhI75ShQnrBWhj4ZsF3qzkZBwEyMHPkp_OGAbMgZ3k7ekhNkhJ1DDlaS5bKavedLl9UR72d7GXW5dE7R4qFVGQEA3L78dtDTYhR-qgoridcWfmx_eKuaD_BXzKQUP2mU3JJx7aomzCpOdLhMLTwJ1LACAAI5j99Iq7kT-VhRcaDp57OehB1gUrUzT7AHUV5ptSVo7ZKTkawYx_ubDijk0cAkZbZDK_R7gFJ-Y4Ij-Nn5dcEPgpPe7SF0dr40IET7Wm-Xd31hWBVa2g

{
  "article": {
    "title": "How to train your dragon",
    "description": "Ever wonder how?",
    "body": "You have to believe",
    "tagList": ["reactjs", "angularjs", "dragons"]
  }
}

###
PUT {{domain}}/api/articles/how-to-train-your-dragon
Content-Type: application/json
Authorization: Token eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzUxMiJ9.eyJleHAiOjMxNTM2MDAwLCJqdGkiOiJTZkx3UHlndmlmWUI0UFRsVEhnS0ZnIiwiaWF0IjoxNjcwODM3MDQ2fQ.LvbRnX9HN94NdYqYZxmkdyVoUIb3umAnjHhqQ-9QY98StxQSqayp2oIS1lPHljL1LFB06-IPLhI75ShQnrBWhj4ZsF3qzkZBwEyMHPkp_OGAbMgZ3k7ekhNkhJ1DDlaS5bKavedLl9UR72d7GXW5dE7R4qFVGQEA3L78dtDTYhR-qgoridcWfmx_eKuaD_BXzKQUP2mU3JJx7aomzCpOdLhMLTwJ1LACAAI5j99Iq7kT-VhRcaDp57OehB1gUrUzT7AHUV5ptSVo7ZKTkawYx_ubDijk0cAkZbZDK_R7gFJ-Y4Ij-Nn5dcEPgpPe7SF0dr40IET7Wm-Xd31hWBVa2g

{
  "article": {
    "title": "Did you train your dragon?"
  }
}

###
GET {{domain}}/api/articles/how-to-train-your-dragon

###
DELETE {{domain}}/api/articles/how-to-train-your-dragon
Content-Type: application/json
Authorization: Token eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzUxMiJ9.eyJleHAiOjMxNTM2MDAwLCJqdGkiOiJqWnpscThiMWl1ZFRyNC1lajFYc0dBIiwiaWF0IjoxNjcwODM2ODYyfQ.Qi_b0fzKMf5hPZfnzbt1RQ4-GTOzwI_KWrYvbZDhJKUy5If2042HF4jmtNC1zlytDeKunJoLOQPUuwCN0TY5R_wpztyOGwDvgy6RBwKViNCdQNLCiksVxsrHq-uhZ2W2kp2yu_JxwcWFj8jQQhdPQmv71Wwtj2rzcwX-Pv5aNVSPsswSx2_cwd46AvFMyMj5srS_U5eytCtEp4VrkFhnBl8423zrvLs26uOAgQjWECThitvkHgBflG8pkoe8ZryWEOyd9-fNKmHotXd5U1XXUlP591dBPaFbwV5PNWzrvbu5ZoIMnqDVCgAqtcEPzLwQonGE3P3DsAnhErC5_bu7zQ